### ISSUE TITLE
Will it support 4.6.5 relase and installation instruction please ?

### ISSUE THREAD

**Issue by amithrh** [totvslabs/couchbase-exporter#12]
Hi all, will it support the older release ? 
Can you guys provide the installation instructions also please ?

**Comment by amithrh** [comment]
@caarlos0 @amalucelli @kungwangtotvs @ffjacob

**Comment by caarlos0** [comment]
> Will it support 4.6.5 

no.

> Can you guys provide the installation instructions also please ?

just download the release and run it with `--help`... let me know if you have more questions...

**Comment by amithrh** [comment]
@caarlos0 Thanks a lot for answering . 
is there any specific reason it wont support version lower than 5 ?

**Comment by caarlos0** [comment]
yes, we don't use it, therefore won't test it nor spend time implementing it.

**Comment by amithrh** [comment]
@caarlos0 fair enough , i have one old 4.6.5 running , i will test it and keep you guys posted..
Nice work 👍

**Comment by caarlos0** [comment]
ok, thanks!

will close this issue for now :)
