### ISSUE TITLE
How can i contribute to this project ?

### ISSUE THREAD

**Issue by amithrh** [totvslabs/couchbase-exporter#13]

**Comment by caarlos0** [comment]
hi @amithrh  are you having problems to setup the development environment?

**Comment by amithrh** [comment]
@caarlos0 i have couchbase running on vms and not as docker image , so was thinking how to use it ?

**Comment by caarlos0** [comment]
that doesn't matter, you can point the exporter to any address using the `--couchbase.url` flag...

**Comment by amithrh** [comment]
@caarlos0, is there any dependency for the release ? like statsmetrics or any other package ?

**Comment by caarlos0** [comment]
no, no dependencies...

**Comment by caarlos0** [comment]
will close this for now, please let me know if you have any further questions :)
