### ISSUE TITLE
so,how to build it

### ISSUE THREAD

**Issue by zhxiaom5** [totvslabs/couchbase-exporter#20]
well ,i try to use go build,but there were so many errors

**Comment by caarlos0** [comment]
Added a documentation for it: https://github.com/totvslabs/couchbase-exporter/blob/master/CONTRIBUTING.md

Other than that, you can download the pre-compiled binaries from the releases page.

If the docs doesn't work for any reason, feel free to reopen.

Cheers

**Comment by zhxiaom5** [comment]
thanks
