### ISSUE TITLE
Support for Couchbase 6.x

### ISSUE THREAD

**Issue by PasqualePuzio** [totvslabs/couchbase-exporter#21]
Hi,

I was wondering if this exporter supports Couchbase 6.x

In the description of the project it's stated that it only supports Couchbase 5, but since there are not major changes in terms of protocol between versions 5 and 6, I was wondering if Couchbase 6 is supported.

Thanks

**Comment by caarlos0** [comment]
Hi @PasqualePuzio 

It may be, although it wasn't tested... feel free to give it a try :)

**Comment by PasqualePuzio** [comment]
Unfortunately I haven't tested it yet (we're using another exporter on the current Couchbase installation) but I'm confident it should work on Couchbase 6 too. Apparently there was no major change that could affect tools already compatible with Couchbase 5.

**Comment by caarlos0** [comment]
let me know what you find out :)

**Comment by antoineserrano** [comment]
Hi @caarlos0, @PasqualePuzio,

I've just tested it here for a whole day with Couchbase v6.0.1, and didn't notice any performance/stability issues so far. All good on the Grafana dashboard end either.

I'll update my message when I'll have the opportunity to run more extensive tests scenarios 😄

**Comment by caarlos0** [comment]
@antoineserrano hey 👋 

any updates?

**Comment by antoineserrano** [comment]
@caarlos0 Hey! Still no issues whatsoever on my end (following up with my initial comment).

The only downside observed is when I want to run the exporter on more than one node (the original idea was to increase availability if the node where the exporter runs goes down).

It results in duplicated Prometheus metrics but I assume it's expected (if not I'm happy to create another issue)...? 

Thanks for your work!

**Comment by caarlos0** [comment]
Yeah that's expected :/ 

I don't know if there is a way to deduplicate it, afaik it doesn't... I don't see anything we could do on the exporter either...
