### ISSUE TITLE
I got it working on Kubernetes. Is that the right way?

### ISSUE THREAD

**Issue by bjethwan** [totvslabs/couchbase-exporter#23]
I got it working on Kubernetes. Check the kubernetes deployment yaml attached. There's some hard-coding for argument passing with couchbase db url and credentials. Is that the right way?

![image](https://user-images.githubusercontent.com/5045325/50631323-e33e3b80-0f69-11e9-848b-fe6e9b78de05.png)

[cb-att-in1-exporter.zip](https://github.com/totvslabs/couchbase-exporter/files/2723221/cb-att-in1-exporter.zip)

**Comment by caarlos0** [comment]
pretty much yes, should be.
