### ISSUE TITLE
Can you please list or document the new metrics with small hint on the usecases for those?

### ISSUE THREAD

**Issue by bjethwan** [totvslabs/couchbase-exporter#24]
Can you please list or document the new metrics with small hint on the usecases for those?
And it would be great if you can compare it with metrics from your older exporter (brunopsoares/prometheus_couchbase_exporter)

**Comment by caarlos0** [comment]
there are way too many metrics. Some of them have the `HELP` set, some still don't (but eventually will).

Either way, will not document that, no. 

You can look into the provided grafana dashboard and prometheus alerts examples.

**Comment by bjethwan** [comment]
cool. thanks.
