### ISSUE TITLE
Dashboard does not work

### ISSUE THREAD

**Issue by ben-foster-cko** [totvslabs/couchbase-exporter#30]
Hi guys,

I tried building the example dashboard in the repo and it seems that most of the panels just have sample data unless I'm missing something?

Also, despite having metrics in prometheus the panels at the top do not work:

![image](https://user-images.githubusercontent.com/19906175/53903455-ae1e9a00-403b-11e9-8328-a9133627e918.png)

Am I missing something or do I need to build the dashboard in some way in order to get the panels correctly pointing to my prometheus data source?

Also is it necessary to create an exporter instance for each node in the cluster?

**Comment by caarlos0** [comment]
Seems like you need to select the instance on the dashboard...

**Comment by caarlos0** [comment]
> Also is it necessary to create an exporter instance for each node in the cluster?

No, one exporter per cluster

**Comment by ben-foster-cko** [comment]
Thanks for getting back to me.

It seems that a number of the panels at the top are hardcoded to the `Prometheus` data source rather than using the `$PROMETHEUS_DS` variable. However, even fixing these, I'm not seeing any data in the top panels.

The instance dropdown doesn't display anything. The value for this variable is sourced from:

```
label_values(couchbase_bucket_basicstats_dataused_bytes, instance)
```

However, this metric doesn't actually exist when I hit the metrics endpoint. The closest I have is:

```
couchbase_bucket_basicstats_dataused{bucket="travel-sample",name="basicstats_dataused"} 82540544.0
```
Also for the other panels such as QPS they seem to default to test data. I had to manually change the datasource to `$PROMETHEUS_DS`.

I also noticed that only one of my buckets is showing in the stats hence my question whether it was necessary to run multiple instances per cluster. Do I need to change the exporter into "cluster mode" or something so that it's aware of the other nodes?

**Comment by caarlos0** [comment]
> It seems that a number of the panels at the top are hardcoded to the `Prometheus` data source rather than using the `$PROMETHEUS_DS` variable. However, even fixing these, I'm not seeing any data in the top panels.

hmm, this is a bug... can you open a PR fixing that?



> However, this metric doesn't actually exist when I hit the metrics endpoint. The closest I have is:

are you sure you are using the right exporter in the latest version?

**Comment by ben-foster-cko** [comment]
Using the latest on Docker. Is it up to date?

**Comment by caarlos0** [comment]
yes, its the same I'm using... and the metric is there 🤔

**Comment by caarlos0** [comment]
closing as its likely something in your config and not on the dashboard itself.
