### ISSUE TITLE
password should be in a config file instead of command line

### ISSUE THREAD

**Issue by ajanwari** [totvslabs/couchbase-exporter#32]
passing password to the exporter via command line is very insecure.

Another exporter had similar issues trying to get listed:
https://github.com/leansys-team/couchbase_exporter/issues/10

**Comment by mator** [comment]
pass it via `COUCHBASE_PASSWORD` environment variable?

https://github.com/totvslabs/couchbase-exporter/blob/fcc6cffb69c7c57109523c0f2b6cba58e2df9ba3/main.go#L24

**Comment by caarlos0** [comment]
as noted, you cam use the env var instead :)
