### ISSUE TITLE
systemStats not supported

### ISSUE THREAD

**Issue by cmaster11** [totvslabs/couchbase-exporter#33]
Hi, I was wondering if there was a specific reason to not map the `systemStats` metrics (e.g. single node CPU utilization).

```
"systemStats": {
  "cpu_utilization_rate": 1.54639175257732,
  "mem_free": 1194868736,
  "mem_total": 1570267136,
  "swap_total": 1610608640,
  "swap_used": 0
  },
```

Thanks,
Alberto

**Comment by caarlos0** [comment]
Hey

I usually grab system metrics through node_exporter, that's why this is not mapped...

**Comment by cmaster11** [comment]
Ah-ha, I see. Because in the case CB is on standalone instances node exporter doesn't help too much. I can happily try to make a PR with them if it's ok for you :)

**Comment by caarlos0** [comment]
> instances node exporter doesn't help too much

I don't get it... can you elaborate?

**Comment by cmaster11** [comment]
Well, if you're fetching metrics from a CB node hosted on an AWS EC2 instance without node_exporter running, you may want to also fetch these metrics. Just as simple as this.

**Comment by caarlos0** [comment]
> Well, if you're fetching metrics from a CB node hosted on an AWS EC2 instance without node_exporter running, you may want to also fetch these metrics. Just as simple as this.

I though you were using some "couchbase as a service" thing hehe

but I guess you can also just install node_exporter, don't you?

**Comment by cmaster11** [comment]
I'm not saying that I personally can't, I was just thinking that since CB offers all the metrics, why not map them all? One thing less to install if not needed (node exporter)

**Comment by caarlos0** [comment]
node exporter has more metrics afaik, has dashboards ready for use and lots of common alerting rules... 

at least that's why I don't feel the need for those metrics from CB too... we just run node_exporter on all machines

**Comment by cmaster11** [comment]
The precise use case is that we're using a different monitoring system, and the hassle of setting up node exporter on all CB machines is not worth the effort, if those simple metrics were available.

**Comment by caarlos0** [comment]
Following the ["yes is forever" rule](https://twitter.com/solomonstre/status/715277134978113536), I rather not do this - or at least not right now.

Thanks for the suggestion either way.
