### ISSUE TITLE
Enchanced cb-exporter client for capturing N1QL query like metrics from different port ReST endpoints

### ISSUE THREAD

**Issue by ashishrana160796** [totvslabs/couchbase-exporter#34]
As per my understanding the client of cb-exporter binds itself to particular port-no. let's say :8091 which is the default one for most of the ReST endpoint queries with a command similar to 
`./couchbase-exporter    ...   --couchbase.url="http://test.server.com:8091 "  ` 
from which we can get  query results for `pools/default`, `pools/nodes` etc. ReST end points.

Let's say we add client _struct_ and collector code for `/active_requests`, `/completed_requests` endpoints for N1QL monitoring as part to extend this cb-exporter. There will be an issue of client still getting bind to only single port here :8093(_as per official  documentation_) for these endpoints. It won't be able to monitor regular stats like `/node` or `/default`  for :8091 port endpoints now.

As, a turn around first we will first normally start cb-exporter for cloud instance with :8091 port-no for regular stat monitoring with cb-exporter OOB.
That will leave no choice but to bind same cloud instance with new cb-exporter process listening to :8093 port for the N1QL query monitoring ReST endpoints after we have added client and collector code for N1QL query monitoring. Hence, this duplication on instances for monitoring N1QL query stats and other regular stats is an issue with current client implementation of `main.go` file.

**Comment by caarlos0** [comment]
sorry, but we don't N1QL, so we are not interested in coding/maintaining such a feature.
