### ISSUE TITLE
Unsettled stats getting displayed with unlinked couchbase instances sharing a common VIP

### ISSUE THREAD

**Issue by ashishrana160796** [totvslabs/couchbase-exporter#35]
Grafana dashboard shows issues with instances that are uniquely part of multiple clusters sharing a common VIP for ReST queries via cb-exporter.

Let's say 7 instances with two clusters, one with 5 CB-VMs & other with 2 CB-VMs sharing common VIP.
Or Let's say 5 instances with one cluster only, one with 4 CB-VMs & one removed out CB-VM instance again sharing some common VIP.

The Couchbase stats are appearing on Grafana dashboard in a flickering manner. For example, server count will alter b/w two values if two clusters are there i.e. it keeps on flickering b/w "5" or "2" as per first case. 
or it will shift b/w value ''1'' and ''4' for the other case with one cluster.

Similar behavior goes for other metrics that are related to cluster level stats. It seems CB-exporter client does scrape from each VM & puts data into Prometheus which might not be a desirable behavior as per above scenarios. Here, I have used instance & CB-VMs interchangeably.

**Comment by caarlos0** [comment]
the exporter talks to a single IP and scrapes the /nodes endpoints to get nodes information.

it does not expect to have multiple clusters behind the same IP.

this seems like an issue on your side.
