### ISSUE TITLE
Image not working in openshift/Kubernetes cluster

### ISSUE THREAD

**Issue by sanupanji** [totvslabs/couchbase-exporter#37]
The docker image is working fine in docker build. But it is not working in K8s/Openshift cluster.

POD Command: 
`<image-entrypoint> --couchbase.url="http://172.23.xxx.xx:8091" --couchbase.username=Admin --couchbase.password=password`

Getting below error in logs:

```
time="2019-09-08T10:40:53Z" level=info msg="starting couchbase-exporter 1.5.1..." source="main.go:38"
--
  | time="2019-09-08T10:40:53Z" level=warning msg="couldn't verify server version compatibility: failed to get nodes: failed to get /pools/nodes: parse \"http://172.23.xxx.xx:8091\"//pools/nodes:  first path segment in URL cannot contain colon" source="couchbase.go:34"
  | time="2019-09-08T10:40:53Z" level=info msg="server listening on :9420" source="main.go:69"

```
same command is working fine in docker with out any error.

**Comment by caarlos0** [comment]
seems like you need to remove the quotes around the url...

anyway, its a problem on your config, not on the exporter itself :)

**Comment by sanupanji** [comment]
As per the document quotes should be there
