### ISSUE TITLE
Read password from the file or environment variable instead of passing it in the command line.

### ISSUE THREAD

**Issue by prabinsh** [totvslabs/couchbase-exporter#41]
Any user logged in can check the password by running ps -ef command. Can password be read from the file or environment variable?

**Comment by mator** [comment]
as per 
https://github.com/totvslabs/couchbase-exporter/blob/fcc6cffb69c7c57109523c0f2b6cba58e2df9ba3/main.go#L24

probably could be used with `COUCHBASE_PASSWORD` environment variable

**Comment by caarlos0** [comment]
yes, you can already use an environment variable for it.
