### ISSUE TITLE
Add installation instructions

### ISSUE THREAD

**Issue by metonymic-smokey** [totvslabs/couchbase-exporter#44]
I recently had to use this exporter and thought the documentation could have some installation instructions - both by downloading from the releases section and building from source(this will also require users to have some prerequisites like go installed on their system). 
  
I'd be willing to do the needful for macOS if the maintainers of the repo think this should be added.
Thanks!

**Comment by caarlos0** [comment]
sounds good! 

Can you open a PR? 

The instructions are pretty much download and execute, or git clone and `make build`...

**Comment by metonymic-smokey** [comment]
@caarlos0 Here's a draft PR!

Thanks!
