### ISSUE TITLE
Image is in CrashLoopBackOff mode

### ISSUE THREAD

**Issue by babai7** [totvslabs/couchbase-exporter#48]
I have taken the image of couchbase-exporter v1.6.0. Tried to run using one existing helm chart. But The Exporter pod is in crashLoopBack Off mode. In the logs, I am getting only -h (help) options. Can someone help?

Here is my deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "couchbase-exporter.fullname" . }}
  labels:
    app: {{ template "couchbase-exporter.name" . }}
    chart: {{ template "couchbase-exporter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "couchbase-exporter.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      annotations:
{{ toYaml .Values.annotations | indent 8 }}
      labels:
        app: {{ template "couchbase-exporter.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: COUCHBASE_HOST
            value: {{ .Values.couchbase.host | quote }}
          - name: COUCHBASE_PORT
            value: {{ .Values.couchbase.port | quote}}
          - name: COUCHBASE_USERNAME
            value: {{ .Values.couchbase.username | quote }}
          {{- if .Values.couchbase.password }}
          - name: COUCHBASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "couchbase-exporter.fullname" . }}
                key: password
          {{- end }}
          - name: PROMETHEUS_PORT
            value: {{ .Values.service.port | quote }}
          ports:
            - name: metrics
              containerPort: {{ .Values.service.port }}
              protocol : TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}

values.yaml
-------------
image:
  repository: totvslabs/couchbase-exporter
  tag: v1.6.0
  pullPolicy: IfNotPresent
couchbase:
  host: ************
  ## Port of the Couchbase cluster to connect to.
  ##
  port: 8091

  ## Username of the Couchbase cluster to connect to.
  ##
  username: Admin

  ## Password of the Couchbase cluster to connect to.
  ##
  password: Admin

**Comment by cleberwarmling** [comment]
@babai7 How are u doing?

In the current state of this exporter, only `COUCHBASE_PASSWORD` can be informed as EnvVar. The rest needs to be informed as Args to the application. You can get the args list [here](https://github.com/totvslabs/couchbase-exporter/blob/85b6cee2aa3754530533f8eb36c218d80aea362e/main.go#L17)

Example:

```
      containers:
      - args:
        - --couchbase.username=Administrator
        - --couchbase.url=http://couchbase:8091
        image: totvslabs/couchbase-exporter:v1.6.0
```

**Comment by babai7** [comment]
@cleberwarmling Thanks for the Info
